openapi: 3.0.0
info:
  title: MultiTenant Company App
  version: 1.0.0
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /tenants:
    get:
      tags:
        - default
      summary: Get All Tenant
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: sandeep@gmail.com
                password: sandeep123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /tenants/create:
    post:
      tags:
        - default
      summary: Create New Company & add new db
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Sandeep Neupane
                email: sandeep@gmail.com
                password: sandeep123
                companyName: Lumbini Tech
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /company/profile:
    get:
      tags:
        - default
      summary: Company Profile Route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/refresh-token:
    post:
      tags:
        - default
      summary: Refresh Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: sandeep@gmail.com
                password: sandeep123
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /tenants/{id}:
    delete:
      tags:
        - default
      summary: Delete the company and tenant
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 63f3616c79d48e0a12142321
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employees/create:
    post:
      tags:
        - default
      summary: Create New Employees to specific tenant
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Dhiren Thapa
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employees:
    get:
      tags:
        - default
      summary: Get all Employees
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}